version: "3"
services:
  vue-app:
    image: node:16-alpine
    container_name: vue-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
